# Generated by Django 5.0.6 on 2024-06-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="slug",
        ),
        migrations.AlterField(
            model_name="stack",
            name="slug",
            field=models.SlugField(
                max_length=100, null=True, unique=True, verbose_name="слаг"
            ),
        ),
    ]
