# Generated by Django 5.0.6 on 2024-06-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_stack_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="stack",
            name="level",
            field=models.SmallIntegerField(
                null=True, verbose_name="Уровень владения стеком"
            ),
        ),
    ]
