# Generated by Django 5.0.6 on 2024-07-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_stack_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="stack",
            name="queue",
            field=models.SmallIntegerField(null=True, verbose_name="Порядок"),
        ),
    ]
