# Generated by Django 5.0.6 on 2024-07-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_stack_queue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stack",
            options={
                "ordering": ["queue"],
                "verbose_name": "Стек",
                "verbose_name_plural": "Стеки",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="img",
            field=models.ImageField(
                null=True, upload_to="portfolio/courses", verbose_name="Аватар курса"
            ),
        ),
    ]
