# Generated by Django 5.0.6 on 2024-07-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_alter_stack_options_course_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="course",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="max_salary",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="min_salary",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="skill",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="stack",
        ),
        migrations.AddField(
            model_name="resume",
            name="city",
            field=models.CharField(
                default="Санкт-Петербург", max_length=100, verbose_name="Город"
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="country",
            field=models.CharField(
                default="Россия", max_length=100, verbose_name="Страна"
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="email",
            field=models.EmailField(
                default="serj2626@mail.ru", max_length=100, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="phone",
            field=models.CharField(
                default="8-953-160-53-84", max_length=100, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="date_end",
            field=models.DateField(null=True, verbose_name="Дата окончания"),
        ),
        migrations.AlterField(
            model_name="course",
            name="date_start",
            field=models.DateField(null=True, verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="experience",
            name="date_end",
            field=models.DateField(null=True, verbose_name="Дата окончания"),
        ),
        migrations.AlterField(
            model_name="experience",
            name="date_start",
            field=models.DateField(null=True, verbose_name="Дата начала"),
        ),
    ]
